name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Configure
        run: cmake --preset release
      - name: Build
        run: cmake --build --preset release
      - name: Test
        run: ctest --test-dir build/release --output-on-failure
